<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prabu Jeyabalan">
<meta name="dcterms.date" content="2025-04-05">

<title>Module 05: Lab 02</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab08-prabu_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab08-prabu_files/libs/quarto-html/quarto.js"></script>
<script src="lab08-prabu_files/libs/quarto-html/popper.min.js"></script>
<script src="lab08-prabu_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab08-prabu_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab08-prabu_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab08-prabu_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab08-prabu_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab08-prabu_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab08-prabu_files/libs/bootstrap/bootstrap-3d02a48b9d94c48ebd73ef71d74f6a01.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#load-the-dataset" id="toc-load-the-dataset" class="nav-link" data-scroll-target="#load-the-dataset"><span class="header-section-number">1</span> Load the Dataset</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">2</span> Feature Engineering</a></li>
  <li><a href="#traintest-split" id="toc-traintest-split" class="nav-link" data-scroll-target="#traintest-split"><span class="header-section-number">3</span> Train/Test Split</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="header-section-number">4</span> Linear Regression</a>
  <ul class="collapse">
  <li><a href="#generalized-linear-regression-summary" id="toc-generalized-linear-regression-summary" class="nav-link" data-scroll-target="#generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</a></li>
  </ul></li>
  <li><a href="#diagnostic-plot" id="toc-diagnostic-plot" class="nav-link" data-scroll-target="#diagnostic-plot"><span class="header-section-number">5</span> Diagnostic Plot</a></li>
  <li><a href="#evaluation" id="toc-evaluation" class="nav-link" data-scroll-target="#evaluation"><span class="header-section-number">6</span> Evaluation</a>
  <ul class="collapse">
  <li><a href="#model-evaluation-plot" id="toc-model-evaluation-plot" class="nav-link" data-scroll-target="#model-evaluation-plot"><span class="header-section-number">6.1</span> Model Evaluation Plot</a></li>
  </ul></li>
  <li><a href="#submission" id="toc-submission" class="nav-link" data-scroll-target="#submission">Submission</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 05: Lab 02</h1>
<p class="subtitle lead">Regression Modeling on Employment Data</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Prabu Jeyabalan </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Boston University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 5, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 9, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="objectives" class="level1 unnumbered">
<h1 class="unnumbered">Objectives</h1>
<ol type="1">
<li>Use <strong>PySpark</strong> to process the Lightcast dataset.</li>
<li>Engineer features from structured columns for salary prediction.</li>
<li>Train <strong>Linear Regression model</strong>.</li>
<li>Evaluate models using <strong>RMSE</strong> and <strong>R²</strong>.</li>
<li>Visualize predictions using diagnostic plots.</li>
<li>Push work to GitHub and submit the repository link.</li>
</ol>
</section>
<section id="setup" class="level1 unnumbered">
<h1 class="unnumbered">Setup</h1>
<p>The instruction below provides you with general keywords for columns used in the lightcast file. See the data schema generated after the load dataset code above to use proper column name. For visualizations, tables, or summaries, please <strong>customize colors, fonts, and styles</strong> as appropriate to avoid a <strong>2.5-point deduction</strong>. Also, <strong>provide a two-sentence explanation</strong> describing key insights drawn from each section’s code and outputs.</p>
<ol type="1">
<li>Follow the steps below as necessary, use your best judgement in importing/installing/creating/saving files as needed.</li>
<li>Create a new Jupyter Notebook in your <code>ad688-sp25-lab08</code> directory named <code>lab08_yourname.ipynb</code>, if the file exists make sure to change the name.</li>
<li>Use your <strong>EC2 instance</strong> for this lab.</li>
<li>Ensure the <code>lightcast_data.csv</code> file is available on the EC2 instance. if not then <strong>Download the dataset</strong></li>
<li><strong>Add the dataset to <code>.gitignore</code></strong> to avoid pushing large files to GitHub. Open your <code>.gitignore</code> file and add:</li>
<li>Make sure to create a virtual environment and install the required Python libraries if needed, don’t forget to activate it:</li>
<li>Install the required Python libraries if needed, you can also use the given requirement file to install the packages to the virtual environment:</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">gdown</span> https://drive.google.com/uc<span class="pp">?</span>id=1V2GCHGt2dkFGqVBeoUFckU4IhUgk4ocQ</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"lightcast_job_postings.csv"</span> <span class="op">&gt;&gt;</span> .gitignore</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="load-the-dataset" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Load the Dataset</h1>
<ol type="1">
<li><strong>Load the Raw Dataset</strong>:
<ul>
<li>Use Pyspark to the <code>lightcast_data.csv</code> file into a DataFrame:</li>
<li>You can reuse the previous code.</li>
<li><span class="uured-bold">Copying code from your friend constitutes plagiarism. DO NOT DO THIS</span>.</li>
</ul></li>
</ol>
<div id="cell-3" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.io <span class="im">as</span> pio</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>pio.renderers.default <span class="op">=</span> <span class="st">"notebook"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize Spark Session</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.appName(<span class="st">"LightcastData"</span>).getOrCreate()</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Data</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> spark.read.option(<span class="st">"header"</span>, <span class="st">"true"</span>).option(<span class="st">"inferSchema"</span>, <span class="st">"true"</span>).option(<span class="st">"multiLine"</span>,<span class="st">"true"</span>).option(<span class="st">"escape"</span>, <span class="st">"</span><span class="ch">\"</span><span class="st">"</span>).csv(<span class="st">"./data/lightcast_job_postings.csv"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># df.printSchema() # comment this line when rendering the submission</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># df.show(5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/04/09 15:15:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
                                                                                </code></pre>
</div>
</div>
</section>
<section id="feature-engineering" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Feature Engineering</h1>
<p>Feature Engineering is a crucial step in preparing your data for machine learning. In this lab, we will focus on the following tasks:</p>
<ol type="1">
<li><strong>Drop rows with missing values</strong> in the target variable and key features.</li>
<li>By now you are already familiar with the code and the data. Based on your understanding please choose any 3 (my code output has 10) variables as:
<ol type="1">
<li>two continuous variables (use your best judgment!)</li>
<li>one categorical.</li>
<li>Your dependent variable (y) is <code>SALARY</code>.</li>
</ol></li>
<li><strong>Convert categorical variables</strong> into numerical representations using <strong>StringIndexer</strong> and <strong>OneHotEncoder</strong>.</li>
<li><strong>Assemble features</strong> into a single vector using <strong>VectorAssembler</strong>.</li>
<li><strong>Split the data</strong> into training and testing sets.</li>
</ol>
<div id="cell-5" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> StringIndexer, OneHotEncoder, VectorAssembler</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml <span class="im">import</span> Pipeline</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows where required columns are null</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MIN_YEARS_EXPERIENCE'</span>, </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MIN_EDULEVELS'</span>, </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'LOT_V6_SPECIALIZED_OCCUPATION_NAME'</span>, </span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SALARY'</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Define categorical variable</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="op">=</span> [<span class="st">'LOT_V6_SPECIALIZED_OCCUPATION_NAME'</span>]</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.<span class="bu">filter</span>(df[<span class="st">"MIN_EDULEVELS"</span>] <span class="op">!=</span> <span class="dv">99</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute percentiles</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>quantiles <span class="op">=</span> df.approxQuantile(<span class="st">"SALARY"</span>, [<span class="fl">0.01</span>, <span class="fl">0.99</span>], <span class="fl">0.0</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>lower_bound, upper_bound <span class="op">=</span> quantiles</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to keep only data within bounds</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.<span class="bu">filter</span>((df[<span class="st">"SALARY"</span>] <span class="op">&gt;=</span> lower_bound) <span class="op">&amp;</span> (df[<span class="st">"SALARY"</span>] <span class="op">&lt;=</span> upper_bound))</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="co"># StringIndexer and OneHotEncoder for categorical variable</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>indexers <span class="op">=</span> [StringIndexer(inputCol<span class="op">=</span>col, outputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_idx"</span>, handleInvalid<span class="op">=</span><span class="st">'skip'</span>) <span class="cf">for</span> col <span class="kw">in</span> categorical_cols]</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>encoders <span class="op">=</span> [OneHotEncoder(inputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_idx"</span>, outputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span>) <span class="cf">for</span> col <span class="kw">in</span> categorical_cols]</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="co"># VectorAssembler for features</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>[<span class="st">'MIN_YEARS_EXPERIENCE'</span>, <span class="st">'MIN_EDULEVELS'</span>] <span class="op">+</span> [<span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span> <span class="cf">for</span> col <span class="kw">in</span> categorical_cols],</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features"</span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Create and apply pipeline</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> Pipeline(stages<span class="op">=</span>indexers <span class="op">+</span> encoders <span class="op">+</span> [assembler])</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pipeline.fit(df).transform(df)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Show sample of transformed dataset</span></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>data.select(<span class="st">'features'</span>, <span class="st">'SALARY'</span>).show(<span class="dv">5</span>, <span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+---------------------------+------+
|features                   |SALARY|
+---------------------------+------+
|(12,[0,1,2],[2.0,2.0,1.0]) |92962 |
|(12,[0,2],[10.0,1.0])      |107645|
|(12,[0,1,5],[6.0,2.0,1.0]) |192800|
|(12,[0,1,5],[12.0,1.0,1.0])|125900|
|(12,[0,1,5],[6.0,2.0,1.0]) |192800|
+---------------------------+------+
only showing top 5 rows
</code></pre>
</div>
</div>
</section>
<section id="traintest-split" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Train/Test Split</h1>
<ul>
<li>Perform a <strong>random split</strong> of the data into training and testing sets.</li>
<li>Set a random seed for reproducibility.</li>
<li>You can choose a number for splitting to your liking, justify your choice.</li>
</ul>
<div id="cell-7" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>train_data, test_data <span class="op">=</span> data.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">777</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((train_data.count(), <span class="bu">len</span>(train_data.columns)))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((test_data.count(), <span class="bu">len</span>(test_data.columns)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(15745, 134)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 35:&gt;                                                         (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(4019, 134)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
</section>
<section id="linear-regression" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Linear Regression</h1>
<ul>
<li>Train a <strong>Linear Regression</strong> model using the training data. <span class="uured-bold">You will run in to an important issue here. Please make an effort in figuring it by yourself. This is one of the most asked interview questions in CapitalOne’s management recruiting program.</span></li>
<li>Evaluate the model on the test data.</li>
<li>Print the coefficients, intercept, R², RMSE, and MAE.</li>
<li>Use the <code>summary</code> object to extract the coefficients and their standard errors, t-values, and p-values.</li>
<li>Create a DataFrame to display the coefficients, standard errors, t-values, p-values, and confidence intervals.</li>
<li>Interpret the coefficients and their significance and explain the model performance metrics.</li>
</ul>
<div id="cell-9" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stderr">
<pre><code>25/04/09 15:55:09 WARN Instrumentation: [ad768bcc] regParam is zero, which might cause numerical instability and overfitting.
[Stage 39:&gt;                                                         (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- Regression Summary ---
Coefficient Standard Errors: ['82.7579', '416.4888', '5021.0075', '5058.9374', '5065.6604', '5062.0326', '5062.8217', '5096.9337', '5118.1055', '5390.6087', '6111.7597', '7351.2224', '5096.4015']
T Values: ['64.4368', '44.7807', '1.9889', '6.7277', '8.1052', '4.1305', '4.9425', '2.3804', '1.7939', '1.9406', '0.5319', '0.3638', '7.4319']
P Values: ['0.0000', '0.0000', '0.0467', '0.0000', '0.0000', '0.0000', '0.0000', '0.0173', '0.0728', '0.0523', '0.5948', '0.7160', '0.0000']
---This is Diagnostic check, No need to print it in the final doc---
Length of features: 4
Length of coefs: 13
Length of se: 13
Length of tvals: 13
Length of pvals: 13</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<section id="generalized-linear-regression-summary" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</h2>
<p>The summary of the Generalized Linear Regression model provides important insights into the model’s performance and the significance of each feature. The coefficients indicate the relationship between each feature and the target variable (salary), while the standard errors, t-values, and p-values help assess the reliability of these estimates.</p>
<ul>
<li>Please interpret them in the context of your data and model.</li>
<li>Feature Names are purposefully not printed in the output. You can use the <code>features</code> variable to print them out.</li>
</ul>
<div id="cell-11" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> LinearRegression</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> Row</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit indexer separately to get labels (used in encoder)</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>indexer_model <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">'LOT_V6_SPECIALIZED_OCCUPATION_NAME'</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                              outputCol<span class="op">=</span><span class="st">'LOT_V6_SPECIALIZED_OCCUPATION_NAME_idx'</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                              handleInvalid<span class="op">=</span><span class="st">'skip'</span>).fit(df)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>occupation_labels <span class="op">=</span> indexer_model.labels  <span class="co"># List of category names</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Building expanded occupation feature names (excluding the base class if dropLast=True)</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>expanded_occupation_features <span class="op">=</span> [<span class="ss">f"Occupation=</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> label <span class="kw">in</span> occupation_labels[<span class="dv">1</span>:]]</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Reconstruct full feature names in the same order as assembled</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>feature_names <span class="op">=</span> [<span class="st">'MIN_YEARS_EXPERIENCE'</span>, <span class="st">'MIN_EDULEVELS'</span>] <span class="op">+</span> expanded_occupation_features</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear regression model</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression(featuresCol<span class="op">=</span><span class="st">'features'</span>, labelCol<span class="op">=</span><span class="st">'SALARY'</span>, regParam<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>lr_model <span class="op">=</span> lr.fit(train_data)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> lr_model.summary</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Extract coefficients and build readable DataFrame</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> [<span class="st">'Intercept'</span>] <span class="op">+</span> feature_names</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>coefs <span class="op">=</span> [lr_model.intercept] <span class="op">+</span> [<span class="bu">float</span>(c) <span class="cf">for</span> c <span class="kw">in</span> lr_model.coefficients]</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> [<span class="va">None</span>] <span class="op">+</span> [<span class="bu">float</span>(s) <span class="cf">for</span> s <span class="kw">in</span> summary.coefficientStandardErrors]</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>tvals <span class="op">=</span> [<span class="va">None</span>] <span class="op">+</span> [<span class="bu">float</span>(t) <span class="cf">for</span> t <span class="kw">in</span> summary.tValues]</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>pvals <span class="op">=</span> [<span class="va">None</span>] <span class="op">+</span> [<span class="bu">float</span>(p) <span class="cf">for</span> p <span class="kw">in</span> summary.pValues]</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [Row(</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    Feature<span class="op">=</span>f,</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>    Coefficient<span class="op">=</span>c,</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    StdError<span class="op">=</span>s,</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>    TValue<span class="op">=</span>t,</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    PValue<span class="op">=</span>p</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>) <span class="cf">for</span> f, c, s, t, p <span class="kw">in</span> <span class="bu">zip</span>(features, coefs, se, tvals, pvals)]</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>coefs_df <span class="op">=</span> spark.createDataFrame(rows)</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>coefs_df.show(truncate<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 45:&gt;                                                         (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------------------------------------+------------------+------------------+-------------------+----------------------+
|Feature                                    |Coefficient       |StdError          |TValue             |PValue                |
+-------------------------------------------+------------------+------------------+-------------------+----------------------+
|Intercept                                  |37893.48670772949 |NULL              |NULL               |NULL                  |
|MIN_YEARS_EXPERIENCE                       |5332.642860786048 |82.75774469676493 |64.43678329231349  |0.0                   |
|MIN_EDULEVELS                              |18650.572200723946|416.48816913548865|44.780557007026744 |0.0                   |
|Occupation=Oracle Consultant / Analyst     |9969.003862011441 |5018.947771009703 |1.9862736806296541 |0.047020266743849515  |
|Occupation=Enterprise Architect            |34017.65943276673 |5056.88537706166  |6.726998319375185  |1.7917223260610626E-11|
|Occupation=General ERP Analyst / Consultant|41040.95420778929 |5063.610020231575 |8.105078006365183  |6.661338147750939E-16 |
|Occupation=SAP Analyst / Admin             |20891.752183774817|5059.981141245512 |4.128820167624641  |3.66510489795413E-5   |
|Occupation=Business Intelligence Analyst   |25005.67219432136 |5060.771791699176 |4.941078796585214  |7.849002350290846E-7  |
|Occupation=Business Analyst (General)      |12115.550093902255|5094.900203099838 |2.3779759388674413 |0.017419835006222906  |
|Occupation=Data Quality Analyst            |9164.239802854954 |5116.079921652049 |1.7912620489117967 |0.0732704687993706    |
|Occupation=Financial Data Analyst          |10443.826873876298|5388.684769946575 |1.9381031401433861 |0.05262850895381854   |
|Occupation=Healthcare Analyst              |3233.666968169282 |6110.0589675834735|0.5292366219909325 |0.5966487821169586    |
|Occupation=Marketing Analyst               |2657.0297938138615|7349.808205399271 |0.36151008564576836|0.7177230216815911    |
+-------------------------------------------+------------------+------------------+-------------------+----------------------+
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<p><em>The linear regression model uses salary as the dependent variable and includes predictors such as years of experience, education level, and specialized occupation. The intercept of approximately $37,893 represents the baseline salary for a Data Analyst (the reference category) with zero years of experience and the minimum education level. While this specific scenario may not occur in practice, it anchors the model and allows for meaningful interpretation of the other coefficients. Importantly, the model uses Data Analyst as the base class for comparison across occupational groups.</em></p>
<p><em>Years of experience and education level both have strong, positive, and statistically significant effects on salary. Each additional year of experience increases predicted salary by about $5,333, and each additional level of education increases it by approximately $18,650, holding other factors constant. These findings align with expectations and underscore the value of experience and advanced education in driving compensation. Their p-values are well below 0.05, indicating high statistical confidence in their effects.</em></p>
<p><em>The model also highlights significant salary differences across occupations relative to Data Analysts. Roles such as General ERP Analyst/Consultant (+$41K), Enterprise Architect (+$34K), and SAP Analyst/Admin (+$29K) command substantially higher salaries, and these differences are statistically significant. Meanwhile, occupations like Healthcare Analyst and Marketing Analyst show modest increases (+$3.2K and +$2.6K respectively), but their p-values suggest these effects are not statistically significant, and may be due to chance. This variation suggests that certain technical and ERP-related roles are rewarded more highly in the market.</em></p>
<div id="cell-13" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions on test set</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> lr_model.transform(test_data)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluation metrics</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>evaluator_r2 <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"r2"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>evaluator_rmse <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"rmse"</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>evaluator_mae <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"mae"</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> evaluator_r2.evaluate(predictions)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> evaluator_rmse.evaluate(predictions)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>mae <span class="op">=</span> evaluator_mae.evaluate(predictions)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print evaluation metrics</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">--- Model Performance on Test Data ---"</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R²: </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE: </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE: </span><span class="sc">{</span>mae<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 49:&gt;                                                         (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
--- Model Performance on Test Data ---
R²: 0.4136
RMSE: 30385.56
MAE: 23743.16</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<p><strong>R² (R-squared): 0.4136</strong></p>
<p><em>This means that approximately 41.36% of the variance in salaries can be explained by the model using the predictors (experience, education level, and occupation). In practical terms, it indicates a moderate fit — the model captures some of the key patterns, but there’s still room for improvement (perhaps by including additional features or non-linear interactions).</em></p>
<p><strong>RMSE (Root Mean Squared Error): 30,385.56</strong></p>
<p><em>This tells that, on average, the model’s predictions deviate from the actual salaries by around $30,385, with larger errors weighted more heavily due to squaring. It provides a general sense of prediction error in the same units as salary, and helps you understand the spread of prediction accuracy.</em></p>
<p><strong>MAE (Mean Absolute Error): 23,743.16</strong></p>
<p><em>This is the average of the absolute errors between predicted and actual salaries. Unlike RMSE, it treats all errors equally and is more robust to outliers. It suggests that on average, your predictions are off by about $23,743, which is a more intuitive measure of average prediction error.</em></p>
</section>
</section>
<section id="diagnostic-plot" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Diagnostic Plot</h1>
<p>Diagnostic plots are essential for evaluating the performance of regression models. In this section, we will create several diagnostic plots to assess the linear regression model’s assumptions and performance. There are four (2*2 grid) main plots we will create, you can use <code>seaborn</code> or <code>matplotlib</code> for this:</p>
<ol type="1">
<li><strong>Predicted vs Actual Plot</strong></li>
<li><strong>Residuals vs Predicted Plot</strong></li>
<li><strong>Histogram of Residuals</strong></li>
<li><strong>QQ Plot of Residuals</strong></li>
</ol>
<div id="cell-16" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert summary predictions to pandas DataFrame</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>df_pred <span class="op">=</span> summary.predictions.select(<span class="st">"SALARY"</span>, <span class="st">"prediction"</span>).toPandas()</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute residuals</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">"residuals"</span>] <span class="op">=</span> df_pred[<span class="st">"SALARY"</span>] <span class="op">-</span> df_pred[<span class="st">"prediction"</span>]</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">"fitted"</span>] <span class="op">=</span> df_pred[<span class="st">"prediction"</span>]</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardized residuals</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>res_mean <span class="op">=</span> df_pred[<span class="st">"residuals"</span>].mean()</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>res_std <span class="op">=</span> df_pred[<span class="st">"residuals"</span>].std()</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">"std_residuals"</span>] <span class="op">=</span> (df_pred[<span class="st">"residuals"</span>] <span class="op">-</span> res_mean) <span class="op">/</span> res_std</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Square root of standardized residuals</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">"sqrt_std_resid"</span>] <span class="op">=</span> np.sqrt(np.<span class="bu">abs</span>(df_pred[<span class="st">"std_residuals"</span>]))</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot diagnostics</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">12</span>))</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 1: Residuals vs Fitted</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"fitted"</span>, y<span class="op">=</span><span class="st">"residuals"</span>, data<span class="op">=</span>df_pred)</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residuals vs Fitted"</span>)</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Fitted Values"</span>)</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 2: QQ Plot</span></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>stats.probplot(df_pred[<span class="st">"residuals"</span>], dist<span class="op">=</span><span class="st">"norm"</span>, plot<span class="op">=</span>plt)</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Normal Q-Q"</span>)</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 3: Scale-Location (sqrt std residuals vs fitted)</span></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"fitted"</span>, y<span class="op">=</span><span class="st">"sqrt_std_resid"</span>, data<span class="op">=</span>df_pred)</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Scale-Location"</span>)</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Fitted Values"</span>)</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"√|Standardized Residuals|"</span>)</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 4: Residuals vs Leverage (approximation using fitted)</span></span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"fitted"</span>, y<span class="op">=</span><span class="st">"std_residuals"</span>, data<span class="op">=</span>df_pred)</span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residuals vs Leverage (approx.)"</span>)</span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Fitted Values"</span>)</span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Standardized Residuals"</span>)</span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-55"><a href="#cb24-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Save and show</span></span>
<span id="cb24-56"><a href="#cb24-56" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb24-57"><a href="#cb24-57" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/glr_diagnostic_classic.png"</span>)</span>
<span id="cb24-58"><a href="#cb24-58" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab08-prabu_files/figure-html/cell-8-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>1.Residuals vs Fitted</strong></p>
<p><em>Shows the residuals (errors) plotted against the model’s predicted salary values.</em></p>
<ul>
<li><p><em>The funnel shape indicates heteroscedasticity (non-constant variance), where residuals spread wider at higher predicted values.</em></p></li>
<li><p><em>Ideally, this plot should look like a random cloud — the curved pattern suggests model misspecification or missing variables.</em></p></li>
</ul>
<p><strong>2. Normal Q-Q Plot</strong></p>
<p><em>Compares the distribution of residuals to a normal distribution.</em></p>
<ul>
<li><p><em>Most points fall along the diagonal line, indicating the residuals are roughly normally distributed, but tails deviate.</em></p></li>
<li><p><em>Deviations at the ends suggest some extreme errors or outliers in the model’s predictions.</em></p></li>
</ul>
<p><strong>3. Scale-Location Plot</strong></p>
<p><em>This is the Scale-Location plot, which helps assess the assumption of constant variance in residuals — also known as homoscedasticity.</em></p>
<ul>
<li><p><em>Here, I’m plotting the square root of the standardized residuals against the fitted salary values. Ideally, we want to see a horizontal spread of points without a clear pattern.</em></p></li>
<li><p><em>In this plot, the residuals appear fairly evenly scattered across the range of predicted salaries, and there’s no strong upward or downward trend. This suggests that the variance of the residuals is relatively stable, which supports the assumption of homoscedasticity. So, based on this plot, I don’t see any major concern regarding unequal error variance in the model.</em></p></li>
</ul>
<p><strong>4. Residuals vs Leverage</strong></p>
<p><em>Assesses influential data points — those that heavily affect the model.</em></p>
<ul>
<li><p>Most points are clustered low and near center, but some outliers on the top-right might have high leverage and influence.</p></li>
<li><p>It is Worth checking individual points for potential outliers or rare combinations of features.</p></li>
</ul>
</section>
<section id="evaluation" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Evaluation</h1>
<p>The evaluation of the model is crucial to understand its performance. In this section, we will calculate and visualize the following metrics: 1. <strong>R² (Coefficient of Determination)</strong>: Indicates how well the model explains the variance in the target variable. 2. <strong>RMSE (Root Mean Squared Error)</strong>: Measures the average magnitude of the errors between predicted and actual values.</p>
<div id="cell-19" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, <span class="bu">pow</span>, sqrt, avg, count</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions on test set</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>pred_glr <span class="op">=</span> lr_model.transform(test_data)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># --- R² using PySpark Evaluator ---</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>r2_eval <span class="op">=</span> RegressionEvaluator(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"r2"</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> r2_eval.evaluate(pred_glr)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co"># --- RMSE using PySpark Evaluator ---</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>rmse_eval <span class="op">=</span> RegressionEvaluator(</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"rmse"</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> rmse_eval.evaluate(pred_glr)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="co"># --- MAE using PySpark Evaluator (optional) ---</span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>mae_eval <span class="op">=</span> RegressionEvaluator(</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"mae"</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>mae <span class="op">=</span> mae_eval.evaluate(pred_glr)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Manually calculate RSS, n, k, BIC (optional) ---</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>residuals_df <span class="op">=</span> pred_glr.withColumn(<span class="st">"residual_sq"</span>, <span class="bu">pow</span>(col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>), <span class="dv">2</span>))</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>rss <span class="op">=</span> residuals_df.agg({<span class="st">"residual_sq"</span>: <span class="st">"sum"</span>}).first()[<span class="dv">0</span>]</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> pred_glr.count()  <span class="co"># number of observations</span></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="bu">len</span>(lr_model.coefficients) <span class="op">+</span> <span class="dv">1</span>  <span class="co"># number of features including intercept</span></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a><span class="co"># --- BIC formula: n * log(RSS/n) + k * log(n) ---</span></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>bic <span class="op">=</span> n <span class="op">*</span> np.log(rss <span class="op">/</span> n) <span class="op">+</span> k <span class="op">*</span> np.log(n)</span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Display evaluation results</span></span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"--- Model Evaluation Metrics ---"</span>)</span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R²: </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE: </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE: </span><span class="sc">{</span>mae<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"BIC: </span><span class="sc">{</span>bic<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 57:&gt;                                                         (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Model Evaluation Metrics ---
R²: 0.4136
RMSE: 30385.56
MAE: 23743.16
BIC: 83073.89</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
<ul>
<li><p><em>The R-squared value is 0.4136,the model is able to explain around 41% of the variance in salaries. That’s a reasonably good starting point, especially considering the complexity and noise in salary data.</em></p></li>
<li><p><em>The RMSE is approximately 30,386, which means that on average, the predicted salaries deviate from the actual salaries by about $30K. Similarly, the MAE is around 23,743, which is a more robust metric showing that the average absolute error is nearly $24K.</em></p></li>
<li><p><em>Finally, the BIC value is 83,073.89. Since BIC penalizes overly complex models, this value gives us a way to compare this model against others in terms of both fit and simplicity — lower BIC is better.</em></p></li>
</ul>
<p><em>Overall, the metrics show that the model performs moderately well, but there’s still room to improve by exploring non-linear models or including additional predictors.</em></p>
<section id="model-evaluation-plot" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="model-evaluation-plot"><span class="header-section-number">6.1</span> Model Evaluation Plot</h2>
<ul>
<li>Display the predicted vs actual salary plot with a red line indicating the ideal fit (y=x).</li>
<li>Use <code>seaborn</code> or <code>matplotlib</code> to create the plot.</li>
<li>Customize the plot with appropriate titles, labels, and legends.</li>
<li>Describe the plot in a few sentences, highlighting key insights and observations.</li>
</ul>
<div id="cell-22" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> GeneralizedLinearRegression</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Fit GLR model instead of LinearRegression</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>glr <span class="op">=</span> GeneralizedLinearRegression(</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">"features"</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">"SALARY"</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span><span class="st">"gaussian"</span>,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    link<span class="op">=</span><span class="st">"identity"</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>glr_model <span class="op">=</span> glr.fit(train_data)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> glr_model.summary</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Predict on test data</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>pred_glr <span class="op">=</span> glr_model.transform(test_data)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Convert predictions to Pandas</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>pandas_df <span class="op">=</span> pred_glr.select(<span class="st">"SALARY"</span>, <span class="st">"prediction"</span>).toPandas()</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Evaluation Metrics</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="co"># R²</span></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>r2_eval <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"r2"</span>)</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> r2_eval.evaluate(pred_glr)</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a><span class="co"># RMSE</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>rmse_eval <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"rmse"</span>)</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> rmse_eval.evaluate(pred_glr)</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC (now available from GLR model)</span></span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>aic <span class="op">=</span> summary.aic</span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a><span class="co"># BIC (manual)</span></span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> pred_glr.count()  <span class="co"># number of observations</span></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="bu">len</span>(glr_model.coefficients) <span class="op">+</span> <span class="dv">1</span>  <span class="co"># predictors incl. intercept</span></span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>rss <span class="op">=</span> summary.deviance  <span class="co"># equivalent to RSS in Gaussian family</span></span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>bic <span class="op">=</span> n <span class="op">*</span> np.log(rss <span class="op">/</span> n) <span class="op">+</span> k <span class="op">*</span> np.log(n)</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Plot</span></span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>pandas_df, x<span class="op">=</span><span class="st">"SALARY"</span>, y<span class="op">=</span><span class="st">"prediction"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, s<span class="op">=</span><span class="dv">50</span>)</span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a><span class="co"># y = x reference line</span></span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>min_val <span class="op">=</span> <span class="bu">min</span>(pandas_df[<span class="st">"SALARY"</span>].<span class="bu">min</span>(), pandas_df[<span class="st">"prediction"</span>].<span class="bu">min</span>())</span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a>max_val <span class="op">=</span> <span class="bu">max</span>(pandas_df[<span class="st">"SALARY"</span>].<span class="bu">max</span>(), pandas_df[<span class="st">"prediction"</span>].<span class="bu">max</span>())</span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>plt.plot([min_val, max_val], [min_val, max_val], color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"Ideal Fit"</span>)</span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Customization</span></span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Actual Salary (USD)"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Predicted Salary (USD)"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.title(</span></span>
<span id="cb30-56"><a href="#cb30-56" aria-hidden="true" tabindex="-1"></a><span class="co">#     f"Predicted vs Actual Salary (GLR Model)\n"</span></span>
<span id="cb30-57"><a href="#cb30-57" aria-hidden="true" tabindex="-1"></a><span class="co">#     f"RMSE = {rmse:.2f} | R² = {r2:.4f} | AIC = {aic:.2f} | BIC = {bic:.2f}",</span></span>
<span id="cb30-58"><a href="#cb30-58" aria-hidden="true" tabindex="-1"></a><span class="co">#     loc="left", fontsize=13, fontweight="bold"</span></span>
<span id="cb30-59"><a href="#cb30-59" aria-hidden="true" tabindex="-1"></a><span class="co"># )</span></span>
<span id="cb30-60"><a href="#cb30-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-61"><a href="#cb30-61" aria-hidden="true" tabindex="-1"></a>plt.title(</span>
<span id="cb30-62"><a href="#cb30-62" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"Predicted vs Actual Salary (GLR Model)</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb30-63"><a href="#cb30-63" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"RMSE = </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss"> | R² = </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss"> | AIC = </span><span class="sc">{</span>aic<span class="sc">:.2f}</span><span class="ss"> | BIC = </span><span class="sc">{</span>bic<span class="sc">:.2f}</span><span class="ss">"</span>,</span>
<span id="cb30-64"><a href="#cb30-64" aria-hidden="true" tabindex="-1"></a>    loc<span class="op">=</span><span class="st">"left"</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">"bold"</span></span>
<span id="cb30-65"><a href="#cb30-65" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-66"><a href="#cb30-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-67"><a href="#cb30-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-68"><a href="#cb30-68" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb30-69"><a href="#cb30-69" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/glr_predicted_vs_actual.png"</span>, dpi<span class="op">=</span><span class="dv">300</span>)</span>
<span id="cb30-70"><a href="#cb30-70" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>25/04/09 15:58:03 WARN Instrumentation: [e25f5bb9] regParam is zero, which might cause numerical instability and overfitting.
[Stage 60:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab08-prabu_files/figure-html/cell-10-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><em>This scatter plot compares the actual salaries (x-axis) with the predicted salaries (y-axis) from the Generalized Linear Regression (GLR) model. The red dashed line represents the ideal scenario where predictions perfectly match the actual values (i.e., y = x).</em></p></li>
<li><p><em>We can see that the points generally follow the upward trend along the ideal line, indicating that the model captures the overall relationship between inputs and salary. However, there’s noticeable vertical scatter around that line, showing prediction errors — especially in the mid-to-high salary range.</em></p></li>
<li><p><em>The model tends to underpredict higher salaries and overpredict some lower ones. This aligns with the moderate R² value of 0.4136 — meaning the model explains about 41% of the variance. The RMSE of ~$30,386 and MAE of ~$23,743 quantify the typical prediction error, while AIC and BIC help compare this model against alternatives.</em></p></li>
</ul>
<p><em>Overall, the model has captured the trend but still shows room for improvement, particularly at the extremes.</em></p>
</section>
</section>
<section id="submission" class="level1 unnumbered">
<h1 class="unnumbered">Submission</h1>
<ol type="1">
<li>Save figures in the <code>_output/</code> folder.</li>
<li>Commit and push code and output files:</li>
</ol>
<div class="sourceCode" id="cb32"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> add .</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> commit <span class="at">-m</span> <span class="st">"Add Lab 08 Salary Prediction models and output"</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> push origin main</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="3" type="1">
<li>Submit your GitHub repository link.</li>
</ol>
</section>
<section id="resources" class="level1 unnumbered">
<h1 class="unnumbered">Resources</h1>
<ul>
<li><a href="https://spark.apache.org/docs/latest/ml-guide.html">PySpark MLlib Docs</a><br>
</li>
<li><a href="https://seaborn.pydata.org/">Seaborn Docs</a><br>
</li>
<li><a href="https://pandas.pydata.org/docs/user_guide/index.html">Pandas User Guide</a></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>